--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/14/2020 10:59:55 AM
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO studentop.auth_group_permissions(id, group_id, permission_id) VALUES
(1, 1, 25),
(2, 1, 28),
(3, 2, 25),
(4, 2, 28),
(5, 3, 25),
(6, 3, 28);