--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/14/2020 11:00:00 AM
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';