--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/14/2020 10:59:59 AM
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO studentop.auth_user_groups(id, user_id, group_id) VALUES
(1, 2, 2),
(2, 3, 2),
(4, 4, 1),
(5, 5, 1),
(3, 6, 3);