--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/14/2020 10:59:58 AM
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO studentop.auth_user(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES
(1, 'pbkdf2_sha256$180000$lWbTAv3obsOS$pkV18WUlSmFp0VRY6r76Q+dk/yjJkEfJas5piyONF24=', '2020-05-14 05:24:54.204101', 1, 'admin', '', '', 'admin@admin.com', 1, 1, '2020-05-14 05:12:02.252929'),
(2, 'pbkdf2_sha256$180000$0hVGhmfZeeYg$VnYWn71k0H+qCPVWdNMToaQehpnMqy6Zy6RtqRsjSLk=', '2020-05-14 05:21:44.936523', 0, 'student1', '', '', '', 1, 1, '2020-05-14 05:14:19'),
(3, 'pbkdf2_sha256$180000$VVOowK9khHck$TMBNcuoIT7lvqP1tNkqeMqtigCg57/n+7vfLR8+s4Y0=', '2020-05-14 05:27:36.767578', 0, 'student2', '', '', '', 1, 1, '2020-05-14 05:15:26'),
(4, 'pbkdf2_sha256$180000$XzrPj7NZ8OvT$UC8k7YklCivHvAfo1XdH665x3JsHcGJSAd4rkeTtvBg=', '2020-05-14 05:23:22.592773', 0, 'teacher1', '', '', '', 1, 1, '2020-05-14 05:16:07'),
(5, 'pbkdf2_sha256$180000$6DLphEkABMhe$UeungARnCM4yc/OMSHcywW7Ma2KeiI6IBIKm5trgO+Y=', NULL, 0, 'teacher2', '', '', '', 1, 1, '2020-05-14 05:16:40'),
(6, 'pbkdf2_sha256$180000$EMyQ6iRJjdEb$bBkY8WioCpstzsOxvdOj0xtVSeZAAp6TEe/GGgyTVu4=', '2020-05-14 05:27:05.630859', 0, 'system_manager', '', '', '', 1, 1, '2020-05-14 05:17:10');