--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/14/2020 11:00:01 AM
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO studentop.django_admin_log(id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) VALUES
(1, '2020-05-14 05:14:19.65332', '2', 'student1', 1, '[{"added": {}}]', 4, 1),
(2, '2020-05-14 05:14:47.828125', '2', 'student1', 2, '[{"changed": {"fields": ["Staff status"]}}]', 4, 1),
(3, '2020-05-14 05:15:27.101562', '3', 'student2', 1, '[{"added": {}}]', 4, 1),
(4, '2020-05-14 05:15:41.863281', '3', 'student2', 2, '[{"changed": {"fields": ["Staff status"]}}]', 4, 1),
(5, '2020-05-14 05:16:07.960937', '4', 'teacher1', 1, '[{"added": {}}]', 4, 1),
(6, '2020-05-14 05:16:18.797851', '4', 'teacher1', 2, '[{"changed": {"fields": ["Staff status"]}}]', 4, 1),
(7, '2020-05-14 05:16:41.430664', '5', 'teacher2', 1, '[{"added": {}}]', 4, 1),
(8, '2020-05-14 05:16:50.297851', '5', 'teacher2', 2, '[{"changed": {"fields": ["Staff status"]}}]', 4, 1),
(9, '2020-05-14 05:17:11.21289', '6', 'system_manager', 1, '[{"added": {}}]', 4, 1),
(10, '2020-05-14 05:18:36.379882', '6', 'system_manager', 2, '[{"changed": {"fields": ["Staff status"]}}]', 4, 1),
(11, '2020-05-14 05:19:06.104492', '1', 'teacher_group', 1, '[{"added": {}}]', 3, 1),
(12, '2020-05-14 05:19:20.701171', '2', 'student_group', 1, '[{"added": {}}]', 3, 1),
(13, '2020-05-14 05:19:41.89746', '3', 'system_manager_group', 1, '[{"added": {}}]', 3, 1),
(14, '2020-05-14 05:20:47.071289', '2', 'student1', 2, '[{"changed": {"fields": ["Groups"]}}]', 4, 1),
(15, '2020-05-14 05:20:59.34375', '3', 'student2', 2, '[{"changed": {"fields": ["Groups"]}}]', 4, 1),
(16, '2020-05-14 05:21:10.856445', '6', 'system_manager', 2, '[{"changed": {"fields": ["Groups"]}}]', 4, 1),
(17, '2020-05-14 05:21:20.486328', '4', 'teacher1', 2, '[{"changed": {"fields": ["Groups"]}}]', 4, 1),
(18, '2020-05-14 05:21:32.013671', '5', 'teacher2', 2, '[{"changed": {"fields": ["Groups"]}}]', 4, 1),
(19, '2020-05-14 05:22:15.652343', '1', 'Hello Teacher 1.', 1, '[{"added": {}}]', 7, 2),
(20, '2020-05-14 05:22:37.49414', '2', 'Hello Teacher 2', 1, '[{"added": {}}]', 7, 2),
(21, '2020-05-14 05:23:13.009765', '3', 'Hello Sir', 1, '[{"added": {}}]', 7, 3),
(22, '2020-05-14 05:23:48.239257', '4', 'Hello Studen1', 1, '[{"added": {}}]', 7, 4),
(23, '2020-05-14 05:27:27.55371', '5', 'Hello Students From Sys manager', 1, '[{"added": {}}]', 7, 6);