--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/14/2020 11:00:04 AM
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO studentop.django_migrations(id, app, name, applied) VALUES
(1, 'contenttypes', '0001_initial', '2020-05-14 05:00:40.65625'),
(2, 'auth', '0001_initial', '2020-05-14 05:00:47.246093'),
(3, 'admin', '0001_initial', '2020-05-14 05:00:59.395507'),
(4, 'admin', '0002_logentry_remove_auto_add', '2020-05-14 05:01:02.501953'),
(5, 'admin', '0003_logentry_add_action_flag_choices', '2020-05-14 05:01:02.884765'),
(6, 'contenttypes', '0002_remove_content_type_name', '2020-05-14 05:01:12.83789'),
(7, 'auth', '0002_alter_permission_name_max_length', '2020-05-14 05:01:15.302734'),
(8, 'auth', '0003_alter_user_email_max_length', '2020-05-14 05:01:17.457031'),
(9, 'auth', '0004_alter_user_username_opts', '2020-05-14 05:01:17.583007'),
(10, 'auth', '0005_alter_user_last_login_null', '2020-05-14 05:01:19.873046'),
(11, 'auth', '0006_require_contenttypes_0002', '2020-05-14 05:01:19.998046'),
(12, 'auth', '0007_alter_validators_add_error_messages', '2020-05-14 05:01:20.208984'),
(13, 'auth', '0008_alter_user_username_max_length', '2020-05-14 05:01:22.110351'),
(14, 'auth', '0009_alter_user_last_name_max_length', '2020-05-14 05:01:23.922851'),
(15, 'auth', '0010_alter_group_name_max_length', '2020-05-14 05:01:25.829101'),
(16, 'auth', '0011_update_proxy_permissions', '2020-05-14 05:01:26.008789'),
(17, 'sessions', '0001_initial', '2020-05-14 05:01:28.210937'),
(18, 'student_module', '0001_initial', '2020-05-14 05:04:57.346679');