--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/14/2020 11:00:06 AM
-- Server version: 8.0.15
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO studentop.student_module_message(id, files, content, subject, last_updated, created, receiver_user_id, sender_user_id) VALUES
(1, '', 'Hell world from Student 1', 'Hello Teacher 1.', '2020-05-14 05:22:15.613281', '2020-05-14 05:22:15.613281', 4, 2),
(2, '', 'Hello World from Student 1', 'Hello Teacher 2', '2020-05-14 05:22:37.467773', '2020-05-14 05:22:37.467773', 5, 2),
(3, '', 'How r u?', 'Hello Sir', '2020-05-14 05:23:12.993164', '2020-05-14 05:23:12.993164', 5, 3),
(4, '', 'From Teacher 1', 'Hello Studen1', '2020-05-14 05:23:48.220703', '2020-05-14 05:23:48.220703', 2, 4),
(5, '', '', 'Hello Students From Sys manager', '2020-05-14 05:27:27.516601', '2020-05-14 05:27:27.516601', 3, 6);