# Generated by Django 3.0.6 on 2020-05-14 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_module.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, help_text='Allowed files Extensions [.pdf,.doc,.docx,.jpg,.png,.xlsx,.xls]', null=True, upload_to='upload/files/', validators=[student_module.validators.validate_file_extension], verbose_name='Upload Coursework or homework')),
                ('content', models.TextField(blank=True, help_text='Maximum character allowed 4000', max_length=4000, null=True)),
                ('subject', models.CharField(help_text='Maximum character allowed 255', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
